name: qsark
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base #-> 4.1.3 newest: 4.2.1
  - conda-forge::r-devtools #-> 2.4.4
  - conda-forge::r-knitr #-> 1.39
  - conda-forge::r-kableextra #-> 1.3.4
  - conda-forge::r-patchwork #-> 1.1.1
  - conda-forge::r-forcats #-> 0.5.1
  - conda-forge::r-ggplot2 #-> 3.3.6
  - conda-forge::r-cowplot #-> 1.1.1
  - conda-forge::r-viridislite #-> 0.4.0
  - conda-forge::r-dplyr #-> 1.0.9
  - conda-forge::r-ggpubr #-> 0.4.0
  - conda-forge::r-ggpattern
  - conda-forge::r-ggnewscale
  - conda-forge::r-markdown
