name: seurat-knitr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.0.3
  - conda-forge::r-seurat=4.0.3
  - conda-forge::r-devtools=2.4.2
  - conda-forge::r-knitr=1.33
  - conda-forge::r-kableextra=1.3.4
  - bioconda::bioconductor-limma=3.46.0
  - conda-forge::r-gprofiler2=0.2.0
  - r-patchwork=1.1.1
  - r-forcats=0.5.1
  - r-ggplot2=3.3.3
  - r-cowplot=1.1.1
  - r-viridislite=0.4.0
  - r-seuratdisk=0.0.9019
  - r-sctransform=0.3.2
  - r-dplyr=1.0.6
